### ISSUE TITLE
publishConnectionDetails support for Azure KV?

### ISSUE THREAD

**Issue by jaylevin** [upbound/crossplane#74]
Hi there,

I am trying to understand the external secret store design and implementation, and have some questions I was hoping I could get an answer for.

In the [external secret store design doc](https://github.com/upbound/crossplane/blob/master/design/design-doc-external-secret-stores.md), it mentions you can publish connection details to AWS Secret Manager via this configuration:
```yaml
spec:
  publishConnectionDetailsTo:
    name: my-db-connection
    metadata:
      tags:
        environment: production
    configRef:
      name: aws-secret-manager-prod
```

However, there is no mention of what the `aws-secret-manager-prod` `Secret` looks like or how it's formatted. Is there any support for Azure KV?

What would the `StoreConfig` look like for AWS Secret Manager/Azure KV? 

Any help would be greatly appreciated.

Thank you!
